### ISSUE TITLE
[Bug] Asurascans: http 404 error while the website is online

### ISSUE THREAD

**Issue by MrAndre96** [AriaMoradi/tachiyomi-unofficial-extensions#6]
## Device information
- Tachiyomi version: r3085
- Android version: Android 10

## Source information
- Name: WP-MangaStream Unofficial
- Extension version: 1.2.2

## Steps to reproduce
1. Open the latest tab for the source

### Expected behavior
Showing the manga

### Actual behavior
Get a 404 error while the website is working

**Comment by AriaMoradi** [comment]
Asura scans has moved to a new theme so it isn't compatible with madara anymore. 
Also their site got hacked and they advised against using the site while its still hacked.

The general policy regarding this repository is that it won't change and bugs won't be fixed unless a willing developer(including myself) invests their time and work to changing it by opening pull requests. Until then this issue will be open.
